const members_2020 = [
	{
		name: "Siddharth Singh",
		image:"images/Alumni_All_Images/Graduating Batch of 2020/Siddharth Singh.jpeg",
		linkedin: "https://www.linkedin.com/in/siddharth-singh-a7232a114/",
		degree: "Computer Science Engineering",
		graduation_year: 2020,
		workplace: "University of Maryland",
		designation: "Graduate Research Assistant",
		additional_info: "",
	},
	{
		name: "Saumo Pal",
		image:"images/Alumni_All_Images/Graduating Batch of 2020/Saumo Pal.jpeg",
		linkedin: "https://www.linkedin.com/in/saumo-pal/",
		degree: "ECE",
		graduation_year: 2020,
		workplace: "Unveild",
		designation: "SDE",
		additional_info: "Cofounder, Gerryeats",
	},

	{
		name: "Dhiraj Kumar",
		image:"images/Alumni_All_Images/Graduating Batch of 2020/Dhiraj Kumar.jpeg",
		linkedin: "https://www.linkedin.com/in/dhiraj-kumar-b18712119/",
		degree: "Industrial and Systems Engineering",
		graduation_year: 2020,
		workplace: "SYMX.AI",
		designation: "CoinSwitch Kuber",
		additional_info: "",
	},
	{
		name: "Amirneni Satakarni",
		image:"images/Alumni_All_Images/Graduating Batch of 2020/Satakarni Amirneni.jpeg",
		linkedin: "https://www.linkedin.com/in/satakarni-amirneni/",
		degree: "Electronics and Electrical Communication Engineering",
		graduation_year: 2020,
		workplace: "Microsoft",
		designation: "",
		additional_info: "",
	},
	{
		name: "Talluri Surya Teja",
		image:"images/Alumni_All_Images/Graduating Batch of 2020/Surya Teja Talluri.jpeg",
		linkedin: "https://www.linkedin.com/in/surya-teja-talluri-383532103/",
		degree: "Electrical Engineering",
		graduation_year: 2020,
		workplace: "MathWorks",
		designation: "",
		additional_info: "",
	},
	{
		name: "Shubham Kumar Dubey",
		image:"images/Alumni_All_Images/Graduating Batch of 2020/Shubham Dubey.jpeg",
		linkedin: "https://www.linkedin.com/in/shubham-dubey-20b828115/",
		degree: "Industrial and Systems Engineering",
		graduation_year: 2020,
		workplace: "American Express",
		designation: "",
		additional_info: "Citi India",
	},
	{
		name: "Rahul Das",
		image:"images/Alumni_All_Images/Graduating Batch of 2020/Rahul Das.jpeg",
		linkedin: "https://www.linkedin.com/in/rahuldas55/",
		degree: "Mathematics",
		graduation_year: 2020,
		workplace: "Rubrik",
		designation: "",
		additional_info: "",
	},
	{
		name: "Ankit Agarwal",
		image:"images/Alumni_All_Images/Graduating Batch of 2020/Ankit Agarwal.jpeg",
		linkedin: "https://www.linkedin.com/in/ankit-agarwal-profile/",
		degree: "Humanities and Social Sciences",
		graduation_year: 2020,
		workplace: "Wells Fargo",
		designation: "",
		additional_info: "Credit Suisse",
	},
	{
		name: "Ojas Agarwal",
		image:"images/Alumni_All_Images/Graduating Batch of 2020/Ojas Agarwal.jpeg",
		linkedin: "https://www.linkedin.com/in/ojasagarwal97/",
		degree: "Ocean Engineering and Naval Architecture",
		graduation_year: 2020,
		workplace: "Sprinklr",
		designation: "",
		additional_info: "",
	},
	{
		name: "Sushovan Haldar",
		image:"images/Alumni_All_Images/Graduating Batch of 2020/Sushovan Haldar.jpeg",
		linkedin: "https://www.linkedin.com/in/sushovan-haldar-23a534113/",
		degree: "Mathematics",
		graduation_year: 2020,
		workplace: "Netradyne",
		designation: "Evalueserve",
		additional_info: "",
	},
	{
		name: "Ruchita Das",
		image:"images/Alumni_All_Images/Graduating Batch of 2020/Ruchita Das.jpeg",
		linkedin: "https://www.linkedin.com/in/ruchitadas3938/",
		degree: "Mathematics",
		graduation_year: 2020,
		workplace: "Amazon",
		designation: "",
		additional_info: "",
	},
	{
		name: "Bharghav D",
		image:"images/Alumni_All_Images/Graduating Batch of 2020/Bhargav Dindukurthi.jpeg",
		linkedin: "https://www.linkedin.com/in/bhargav-dindukurthi/",
		degree: "Industrial and Systems Engineering",
		graduation_year: 2020,
		workplace: "Cadence Design Systems",
		designation: "Adobe",
		additional_info: "Stanford University",
	},
	{
		name: "Rishav Sharma",
		image:"images/Alumni_All_Images/Graduating Batch of 2020/Rishav Sharma.jpeg",
		linkedin: "https://www.linkedin.com/in/rishav-sharma-9762a6131/",
		degree: "Civil Engineering",
		graduation_year: 2020,
		workplace: "Millenium",
		designation: "JPMorgan Chase & Co",
		additional_info: "",
	},
	{
		name: "G Vishal",
		image:"images/Alumni_All_Images/Graduating Batch of 2020/Vishal Garimella.jpeg",
		linkedin: "https://www.linkedin.com/in/vishal-garimella-674b56125/",
		degree: "Computer Science and Engineering",
		graduation_year: 2020,
		workplace: "Microsoft",
		designation: "Goldman Sachs",
		additional_info: "",
	},
	{
		name: "Soumava Paul",
		image:"images/Alumni_All_Images/Graduating Batch of 2020/Soumava Paul.jpeg",
		linkedin: "https://www.linkedin.com/in/mvp18/",
		degree: "Electrical Engineering",
		graduation_year: 2020,
		workplace: "Inria",
		designation: "Universität des Saarlandes",
		additional_info: "",
	},
	{
		name: "Sanskar Agarwal",
		image:"images/Alumni_All_Images/Graduating Batch of 2020/Sanskar A.jpeg",
		linkedin: "https://www.linkedin.com/in/sanskar97/",
		degree: "Electrical Engineering",
		graduation_year: 2020,
		workplace: "Preimage",
		designation: "Intel Labs",
		additional_info: "",
	},
	{
		name: "L Pavan Kumar",
		image:"images/Alumni_All_Images/Graduating Batch of 2020/Lanke Pavan Kumar.jpeg",
		linkedin: "https://www.linkedin.com/in/lanke-pavan-kumar-535a23148/",
		degree: "Electronics and Electrical Communication Engineering",
		graduation_year: 2020,
		workplace: "Audit Partnership Ltd",
		designation: "Brillio",
		additional_info: "",
	},
	{
		name: "Anjali Jha",
		image:"images/Alumni_All_Images/Graduating Batch of 2020/Anjali Jha.jpeg",
		linkedin: "https://www.linkedin.com/in/anjalijha167/",
		degree: "Industrial and Systems Engineering",
		graduation_year: 2020,
		workplace: "Woodline Partners",
		designation: "Goldman Sachs",
		additional_info: "University of California, Berkeley",
	},
	{
		name: "Chinmay Sawkar",
		image:"images/Alumni_All_Images/Graduating Batch of 2020/Chinmay Sawkar.jpeg",
		linkedin: "https://www.linkedin.com/in/chinmay997/",
		degree: "Manufacturing",
		graduation_year: 2020,
		workplace: "Apple",
		designation: "SDE Intern",
		additional_info: "Graduate Teaching Assistant, Texas A&M University",
	},
];

export default members_2020;
