const members_2016 = [
	{
		name: "Sirin Sanchay",
		image: "images/Alumni_All_Images/Graduating Batch of 2016/Sirin.jpeg",
		linkedin: "https://www.linkedin.com/in/sirin-sanchay-8b7a37256/",
		degree: "Electrical and Electronics Engineering",
		year: 2016,
		workplace: "Indian Railways",
		designation: "Senior Associate",
		additional_info: "MTech",
	},
	{
		name: "Pradeepta Das",
		image: "images/Alumni_All_Images/Graduating Batch of 2016/Pradeepta.jpeg",
		linkedin: "https://www.linkedin.com/in/daprad/",
		degree: "Electrical Engineering",
		year: 2016,
		workplace: "J.P Morgan",
		designation: "Senior Associate",
		additional_info: "Masters",
	},
	{
		name: "Apurva Swarnakar",
		image: "images/Alumni_All_Images/Graduating Batch of 2016/Apurva.jpeg",
		linkedin: "https://www.linkedin.com/in/apurva-swarnakar/",
		degree: "Electronics and Electrical Communication Engineering",
		year: 2016,
		workplace: "Sprinklr",
		designation: "Senior Associate",
		additional_info: "Masters",
	},

	{
		name: "D Venkata Sainath",
		image: "images/Alumni_All_Images/Graduating Batch of 2016/Venkata.jpeg",
		linkedin: "https://www.linkedin.com/in/venkatasainath/",
		degree: "Electical Engineering",
		year: 2016,
		workplace: "InvAscent",
		designation: "Associate",
		additional_info: "MBA",
	},
	{
		name: "SPLV Pavan",
		image: "images/Alumni_All_Images/Graduating Batch of 2016/Pawan.jpeg",
		linkedin: "https://www.linkedin.com/in/pawan-splv-b2a4537a/",
		degree: "Mechanical Engineering",
		year: 2016,
		workplace: "Tira",
		designation: "Senior Associate",
		additional_info: "Product Manager , Cars24 | Product Manager, HCL",
	},

	{
		name: "Ayush Kumar Singh",
		image: "images/Alumni_All_Images/Graduating Batch of 2016/Ayush.jpeg",
		linkedin: "https://www.linkedin.com/in/ayush-singh-0145137b/",
		degree: "Mechanical Engineering",
		year: 2016,
		workplace: "Goldman Sachs",
		designation: "Associate",
		additional_info: "Senior Consultant ,EXL",
	},
	{
		name: "Rakesh Reddy",
		image: "images/Alumni_All_Images/generic profile avatar.png",
		linkedin: "https://www.linkedin.com/in/rakeshreddygunukula/",
		degree: "Electrical Engineering",
		year: 2016,
		workplace: "Forest Creek Capital LLC",
		designation: "Governor(2015-16)",
		additional_info: "Analyst, American Express MPS",
	},
	{
		name: "Mayank Manish",
		image: "images/Alumni_All_Images/generic profile avatar.png",
		linkedin: "https://www.linkedin.com/in/mayank-manish-3960a060/",
		degree: "Computer Science Engineering",
		year: 2016,
		workplace: "",
		designation: "Senior Associate",
	},
];

export default members_2016;
