const members_2021 = [
	{
		name: "Rushikesh Wayal",
		image:"images/Alumni_All_Images/Graduating Batch of 2021/Rushikesh Wayal.jpeg",
		linkedin: "https://www.linkedin.com/in/rushikesh-wayal/",
		degree: "Electronics and Electrical Communication Engineering",
		graduation_year: 2021,
		workplace: "AlphaGrep",
		designation: "",
		additional_info: "",
	},
	{
		name: "Dibya Prakash Das",
		image:"images/Alumni_All_Images/Graduating Batch of 2021/Dibya Prakash Das.jpeg",
		linkedin: "https://www.linkedin.com/in/dibya-prakash-das/",
		degree: "Mathematics",
		graduation_year: 2021,
		workplace: "Zepto",
		designation: "",
		additional_info: "",
	},
	{
		name: "Supriya Gupta",
		image:"images/Alumni_All_Images/Graduating Batch of 2021/Supriya Gupta.jpeg",
		linkedin: "https://www.linkedin.com/in/supr1ya-gupta/",
		degree: "Industrial and Systems Engineering",
		graduation_year: 2021,
		workplace: "JP Mogan Chase & Co",
		designation: "",
		additional_info: "",
	},
	{
		name: "Anju Joon",
		image:"images/Alumni_All_Images/Graduating Batch of 2021/Anju Joon.jpeg",
		linkedin: "https://www.linkedin.com/in/anju-joon-27099a128/",
		degree: "Humanities and Social Sciences",
		graduation_year: 2021,
		workplace: "ANU",
		designation: "",
		additional_info: "",
	},
	{
		name: "Sounak Saha",
		image:"images/Alumni_All_Images/Graduating Batch of 2021/Sounak Saha.jpeg",
		linkedin: "https://www.linkedin.com/in/sounak-saha-a8840ab8/",
		degree: "Biotechnology",
		graduation_year: 2021,
		workplace: "UIUC RNA Club",
		designation: "",
		additional_info: "",
	},
	{
		name: "Kankana Haldar",
		image:"images/Alumni_All_Images/Graduating Batch of 2021/Kankana Haldar.jpeg",
		linkedin: "https://www.linkedin.com/in/kankana-haldar-3313a6147/",
		degree: "Electrical Engineering",
		graduation_year: 2021,
		workplace: "American Express",
		designation: "",
		additional_info: "",
	},
];

export default members_2021;
