const members_2019 = [
	{
		name: "Ritwika Chowdhury",
		image:"images/Alumni_All_Images/Graduating Batch of 2019/Ritwika Chowdhury.jpeg",
		linkedin: "https://www.linkedin.com/in/ritwika-chowdhury-a70201112/",
		degree: "Electronics and Electrical Communication Engineering",
		graduation_year: 2019,
		workplace: "unScript.AI",
		designation: "Research Scientist, Intel Labs",
	},
	{
		name: "Raghav Sonavane",
		image:
			"images/Alumni_All_Images/Graduating Batch of 2019/Raghav Sonavane.jpeg",
		linkedin: "https://www.linkedin.com/in/raghavsonavane/",
		degree: "Electronics and Electrical Communication Engineering",
		graduation_year: 2019,
		workplace: "Uber",
		designation: "",
	},
	{
		name: "Rahul Barnwal",
		image:
			"images/Alumni_All_Images/Graduating Batch of 2019/Rahul Barnwal.jpeg",
		linkedin: "https://www.linkedin.com/in/rahul-barnwal-774169a8/",
		degree: "Mathematics",
		graduation_year: 2019,
		workplace: "J.P Morgan",
		designation: "",
	},
	{
		name: "Mohit Pokharna",
		image:
			"images/Alumni_All_Images/Graduating Batch of 2019/Mohit Pokharna.jpeg",
		linkedin: "https://www.linkedin.com/in/mohitpokharna/",
		degree: "Mathematics",
		graduation_year: 2019,
		workplace: "Mercari",
		designation: "",
	},
	{
		name: "Devanand Kedia",
		image:
			"images/Alumni_All_Images/Graduating Batch of 2019/Devanand Kedia.jpeg",
		linkedin: "https://www.linkedin.com/in/devanandkedia/",
		degree: "Electrical Engineer",
		graduation_year: 2019,
		workplace: "HSBC",
		designation: "",
	},
	{
		name: "Rameshwar Bhaskaran",
		image:
			"images/Alumni_All_Images/Graduating Batch of 2019/Rameshwar Bhaskaran.jpeg",
		linkedin: "https://www.linkedin.com/in/rameshwarbhaskaran/",
		degree: "Computer Science Engineering",
		graduation_year: 2019,
		workplace: "Meta",
		designation: "Senior Software Engineer",
	},
	{
		name: "Shivam Agarwal",
		image:
			"images/Alumni_All_Images/Graduating Batch of 2019/Shivam Agarwal.jpeg",
		linkedin: "https://www.linkedin.com/in/shivam207/",
		degree: "Mathematics",
		graduation_year: 2019,
		workplace: "Infiswift Technologies",
		designation: "Computer Vision Engineer, Accenture",
	},
	{
		name: "Arnab Bir",
		image: "images/Alumni_All_Images/Graduating Batch of 2019/Arnab Bir.jpeg",
		linkedin: "https://www.linkedin.com/in/arnabbir/",
		degree: "Mathematics",
		graduation_year: 2019,
		workplace: "Phonepe",
		designation: "Google, Flipkart",
	},
	{
		name: "Utkarsh Parasrampuria",
		image:
			"images/Alumni_All_Images/Graduating Batch of 2019/Utkarsh Parasrampuria.jpeg",
		linkedin: "https://www.linkedin.com/in/utkarsh-parasarampuria/",
		degree: "Computer Science Engineering",
		graduation_year: 2019,
		workplace: "Rawky Studios",
		designation: "Executive Director, Internship, Intuit India",
	},
	{
		name: "Piyush Kumar Singh",
		image:
			"images/Alumni_All_Images/Graduating Batch of 2019/Piyush Singh.jpeg",
		linkedin: "https://www.linkedin.com/in/piyushk95/",
		degree: "Civil Engineering",
		graduation_year: 2019,
		workplace: "Morgan Stanley",
		designation: "Blackrock",
	},
	{
		name: "Tejus Gupta",
		image: "images/Alumni_All_Images/Graduating Batch of 2019/Tejus Gupta.jpeg",
		linkedin: "https://www.linkedin.com/in/tejus-gupta-03baa3102/",
		degree: "Computer Science Engineering",
		graduation_year: 2019,
		workplace: "Research Assistant, Robotics Institute",
		designation: "",
		additional_info: "",
	},
	{
		name: "Ashwary Anand",
		image:
			"images/Alumni_All_Images/Graduating Batch of 2019/Ashwary Anand.jpeg",
		linkedin: "https://www.linkedin.com/in/ashwary-anand-a83642107/",
		degree: "Mechanical",
		graduation_year: 2019,
		workplace: "Rapyuta Robotics",
		designation: "",
		additional_info: "",
	},
	{
		name: "Pranjal Jain",
		image:
			"images/Alumni_All_Images/Graduating Batch of 2019/Pranjal Jain.jpeg",
		linkedin: "https://www.linkedin.com/in/pranjal-jain-8759a1b4/",
		degree: "Chemical Engineering",
		graduation_year: 2019,
		workplace: "JP Morgan Chase &Co",
		designation: "",
		additional_info: "",
	},
	{
		name: "Aniket Gattani",
		image:
			"images/Alumni_All_Images/Graduating Batch of 2019/Aniket Gattani.jpeg",
		linkedin: "https://www.linkedin.com/in/aniket-gattani-7692b0104/",
		degree: "Mechanical Engineering",
		graduation_year: 2019,
		workplace: "Google",
		designation: "",
		additional_info: "Rice University",
	},
	{
		name: "Abhinav Arun",
		image:
			"images/Alumni_All_Images/Graduating Batch of 2019/Abhinav Arun.jpeg",
		linkedin: "https://www.linkedin.com/in/abhinav-arun-432341117/",
		degree: "Mechanical Engineering",
		graduation_year: 2019,
		workplace: "Prudential Financial",
		designation: "Innovaccer",
		additional_info: "Georgia Institute of Technology",
	},
	{
		name: "Satyam Behera",
		image:
			"images/Alumni_All_Images/Graduating Batch of 2019/Satyam Behera.jpeg",
		linkedin: "https://www.linkedin.com/in/satyam-behera-916084114/",
		degree: "Metallurgical and Materials Engineering",
		graduation_year: 2019,
		workplace: "MasterCard",
		designation: "ExxonMobil",
		additional_info: "IIM Calcutta",
	},
	{
		name: "Tushar Sinha",
		image:
			"images/Alumni_All_Images/Graduating Batch of 2019/Tushar Sinha.jpeg",
		linkedin: "https://www.linkedin.com/in/tushar-sinha-a0904412a/",
		degree: "(Instrumentation Engineering) Electrical Engineering",
		graduation_year: 2019,
		workplace: "Uber",
		designation: "JPMorgan Chase & Co",
		additional_info: "",
	},
	{
		name: "Kanav Anand",
		image: "images/Alumni_All_Images/Graduating Batch of 2019/Kanav Anand.jpeg",
		linkedin: "https://www.linkedin.com/in/kanavanand/",
		degree: "Industrial and Systems Engineering",
		graduation_year: 2019,
		workplace: "Co-founder, Flick",
		designation: "Apna, American Express",
		additional_info: "",
	},
];

export default members_2019;
